### PR TITLE
v0.3.z base on Godwoken Kicker v0.3.1-rc1 

### PR DESCRIPTION
**Pull request by Flouse**
https://github.com/RetricSu/godwoken-kicker/releases/tag/v0.3.1-rc1

### CODE REVIEW

**Comment by jjyr** [comment]
Can we merge this?

**Comment by Flouse** [comment]
Not yet.

### Version: godwoken-kicker/releases/tag/v0.3.1-rc1

```
--------------------------------------------------------------------------------
TEST                                                       | STATUS   | DURATION  
CkbAsset                                                   | Passed   | 393 s     
SudtAsset                                                  | Failed   | 560 s     
Polyjuice                                                  | Failed   | 0 s     
```

The SUDT withdrawal function is **NOT stable** now.

#### Error
Submitting l2 block error: JSONRPC error: Server error: **TransactionFailedToResolve**: Resolve failed Unknown

#### Log
```log
waiting for layer 2 block producer withdrawal ... 295 seconds
timeout for waiting withdraw success in godwoken, please check with account id: 2 by your self.

---


godwoken_1   |     Submitted l2 block 60 in tx cd0c598c42acc298a0790dc381fab0bf472f3ca8bdb8136b1b49b77b1731c12b
godwoken_1   |     
godwoken_1   | [2021-06-10T15:26:56Z INFO  gw_block_producer::runner] received new layer1 block 380, e122e81d4e27882e1e9d3394985996634217114889b45dae2cb3c99d3a887d21
godwoken_1   | [2021-06-10T15:26:59Z INFO  gw_block_producer::runner] received new layer1 block 381, 9e9d8ade43a16c4fe1b4afd4f5a7e1cd7f972d23877f6bdb5b217466a3d5cadb
godwoken_1   | [2021-06-10T15:27:05Z INFO  gw_block_producer::runner] received new layer1 block 382, f3ae9090bacbf436903bf8673324b96b95453b7644e7870c91bbabacd92e4ebd
godwoken_1   | [2021-06-10T15:27:11Z INFO  gw_block_producer::runner] received new layer1 block 383, 971214aacbff6505ab54e2b2648e8faa404de6c097259950cd8729fd54043095
godwoken_1   | [2021-06-10T15:27:14Z INFO  gw_block_producer::runner] received new layer1 block 384, f70f494c075b0ac00371f7586849e70c7f5a07ce647f43c1c345736f8241d64d
godwoken_1   | [2021-06-10T15:27:14Z INFO  gw_block_producer::block_producer] produce new block #60 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 1)
godwoken_1   | [2021-06-10T15:27:14Z ERROR gw_block_producer::block_producer] Submitting l2 block error: JSONRPC error: Server error: TransactionFailedToResolve: Resolve failed Unknown([OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000), OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80001000000), OutPoint(0x70bfcdb521930ba8de3ca5b8ae9094a7a90f1dbdbf76af5fa9ee7336fcf0ca8102000000), OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000)])
godwoken_1   | [2021-06-10T15:27:20Z INFO  gw_block_producer::runner] received new layer1 block 385, 979868aac87102ad7d2b6dca0dbee9da9f9808c11bcef5a1e2ce20b662088a2c
godwoken_1   | [2021-06-10T15:27:20Z INFO  gw_block_producer::block_producer] produce new block #61 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 0)
godwoken_1   | [2021-06-10T15:27:20Z INFO  gw_block_producer::block_producer] 
godwoken_1   |     Submitted l2 block 61 in tx f1cef95bf84c4f9d87df2ca40cd24256f337bf320d7a65707bb126be3c9ab2d2
godwoken_1   |     
godwoken_1   | [2021-06-10T15:27:26Z INFO  gw_block_producer::runner] received new layer1 block 386, 6f2e322f6455df9491134afb42f8deff123ba17a1e7ceb74708c36107856706f
```

---

But sometimes, it works.
```
--------------------------------------------------------------------------------
TEST                                                       | STATUS   | DURATION  
SudtAsset                                                  | Passed   | 258 s    
```

**Comment by jjyr** [comment]
Seems like a bug of godwoken, what is the outpoint 0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000？

Can you identify which cell causes this error? you can query this cell in your local environment.

**Comment by Flouse** [comment]
```
godwoken_1   | [2021-06-10T15:27:14Z ERROR gw_block_producer::block_producer] 
Submitting l2 block error: JSONRPC error: Server error: TransactionFailedToResolve: Resolve failed Unknown([
    OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000), 
    OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80001000000), 
    OutPoint(0x70bfcdb521930ba8de3ca5b8ae9094a7a90f1dbdbf76af5fa9ee7336fcf0ca8102000000), 
    OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000)])
```

---

### l1TxHash
0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c800
### transaction with status: 
```Json
{
    "transaction": {
        "cell_deps": [
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xb3de3dea316f8c04da9e04f81ee08ab871746046292b90288602b07ba88b67b7"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xc2d0b850618aa4bc6f833b6dfe921a6e718d376d24882d45d805149fd7290976"
                }
            },
            {
                "dep_type": "dep_group",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0x2db1b175e0436966e5fc8dd5cdf855970869b37a6c556e00e97ccb161c644eb5"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0x78387eaa0657e6a71b36f299fc515320d2fa2d9d452cd7d74dc9d8308cac3652"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xb50ba45f9c5d9e4a6b283c0f6fe50975dafebfc6b552107f03d49d3168efbdb2"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x1",
                    "tx_hash": "0x4954b63327fb2157c32c4606cdd5ab9556cf9bb9c8a8ec452c14b84b5d00a2a5"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xe29e1370b02ca3bcb03150b72b22258e1618012e42c6110037d9c669202d80d8"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0x8be789e7555a67b77c6f2112b29debc32c16b90b24e30dec4a8c99627f631176"
                }
            }
        ],
        "hash": "0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c800",
        "header_deps": [],
        "inputs": [
            {
                "previous_output": {
                    "index": "0x0",
                    "tx_hash": "0x8be789e7555a67b77c6f2112b29debc32c16b90b24e30dec4a8c99627f631176"
                },
                "since": "0x4000000060c22ec0"
            },
            {
                "previous_output": {
                    "index": "0x1",
                    "tx_hash": "0x8be789e7555a67b77c6f2112b29debc32c16b90b24e30dec4a8c99627f631176"
                },
                "since": "0x0"
            },
            {
                "previous_output": {
                    "index": "0x0",
                    "tx_hash": "0x4861b1d0aec7b1c9fcb60602bcc174bdc2e8b943dfd89fa4d0d9bd4933a12927"
                },
                "since": "0x0"
            },
            {
                "previous_output": {
                    "index": "0x2",
                    "tx_hash": "0x8fdea291b961e6b60e9281e35e88c62f6d83739f5142e1de3eb5c635c822d8b3"
                },
                "since": "0x0"
            }
        ],
        "outputs": [
            {
                "capacity": "0x82c1f7f00",
                "lock": {
                    "args": "0x7840d20d8828ee4ea694fbc95f73e1513681e5d8ee3d866a72068c96ff25a25b6e2999a011d119bef85e3de804976d0c57d4d4a4c673f909024c266cf9e897c5",
                    "code_hash": "0x3bcd5dd6af0c2c1d865f787e648044f90177382288072c61c57bc989a2375f16",
                    "hash_type": "type"
                },
                "type": {
                    "args": "0x4912ea97674f287bc916f36c458cf5737214c370b9ffa9eea71836bda7248ff2",
                    "code_hash": "0x22034c8ad0710a83ba28bd41cd1cb1a0786e0fd984cbd20d81ba3219d52a1932",
                    "hash_type": "type"
                }
            },
            {
                "capacity": "0x3b9aca000",
                "lock": {
                    "args": "0x5f8e37cad738cd4d2e4317e57ece7809a794e31fcfb2694b11dffe2b739f7ac3",
                    "code_hash": "0xf70aa98a96fba847185be1b58c1d1e3cae7ad91f971eecc5749799d5e72939f0",
                    "hash_type": "type"
                },
                "type": {
                    "args": "0x6e2999a011d119bef85e3de804976d0c57d4d4a4c673f909024c266cf9e897c5",
                    "code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944",
                    "hash_type": "type"
                }
            },
            {
                "capacity": "0x318bde500",
                "lock": {
                    "args": "0x8c71916faa3b18d34e709575722810c65ba4d66ff005c4b7112bbf4e54f1afe43bab60cef4af81a87b0386f29bbf1dd0f6fe71c9fe1d84ca37096a6284d3bdaf3b00000000000000",
                    "code_hash": "0xe70a7c0e8f5e18bbd6b6e5785df7e0dd5c41cc9d3c328ccb6f24bfddc96f970d",
                    "hash_type": "type"
                },
                "type": null
            },
            {
                "capacity": "0x12471342aec4",
                "lock": {
                    "args": "0x43d509d97f26007a285f39241cffcd411157196c",
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type"
                },
                "type": null
            }
        ],
        "outputs_data": [
            "0x72c14a3ca6d07c78c658113396865fdab50fadeec82f5abe82da7d74b348f982f276e77c597902664a09ace6c5a5e6524d6f23bbb96c96c40fdf8bac4fa7385007000000f53479f3bf87f5a5bd9ee2103894e48d97109e7c3bcefb05d415e5ca15d0b2233c0000000000000000000000000000000000000000000000000000000000000000000000000000002aeaa2edc0f63ff2ca7227f311477e8cc6eaaead0577c6d1586af166ccc901cb270000000000000000",
            "0xc02ec26000000000c02ec26000000000000000000000",
            "0x",
            "0x"
        ],
        "version": "0x0",
        "witnesses": [
            "0x630500001000000055000000550000004100000057fb4a811c84886d5464408ae39bd7f96f86d03301fe367e76ca30b57312ffe8786faf242bab2686fc2db903b3b23c61d5e144ae6ab60e8a75fa10360317c18a010a050000000000000605000010000000fe04000002050000ee0400001c00000060010000f4020000370400003b040000ea040000440100002c0000003400000038000000580000007800000080000000a4000000c8000000cc000000f00000003b00000000000000000000001b1c24da6a050a22408ba09e551e64dfd709508d8d35b8e166078c034e7cf8ae3bab60cef4af81a87b0386f29bbf1dd0f6fe71c9fe1d84ca37096a6284d3bdaf6b1d88f679010000f276e77c597902664a09ace6c5a5e6524d6f23bbb96c96c40fdf8bac4fa7385007000000f276e77c597902664a09ace6c5a5e6524d6f23bbb96c96c40fdf8bac4fa738500700000000000000000000000000000000000000000000000000000000000000000000000000000000000000540000001000000030000000340000000000000000000000000000000000000000000000000000000000000000000000000000005f46190489d7e717c833464cc603efff8b8faaa40e8fa930446e1acf4237a4a8940100001800000064000000b0000000fc000000480100004c0000000c0000002c000000f6322ad407970b5e1bfa19265a872640ce4bfedb74bcdbc3ac9a757b4ba682a6862ac8bc330000000000000000000000000000000000000000000000000000004c0000000c0000002c0000003410e0a1978f78d51d30a72abcd592a0017257376c0f190187392bdf7c2aab7906000000000000000000000000000000000000000000000000000000000000004c0000000c0000002c000000fdaefa88d2b1217a6e862aba8dd1a750e87d7250e8bc08b8f77f862a7fcae3bf02000000000000000000000000000000000000000000000000000000000000004c0000000c0000002c000000c98ed5e26bff6b6c9a58cb888214f62805e3fd30aeaf68ff2ffe0eeb841849ccdf1774ba3f0000000000000000000000000000000000000000000000000000004c0000000c0000002c000000020000000100000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000003f0100004c500207c85fdf4e4ee8dbdc4b802452c3400fe951fbec21703969e2bda35f47ec62165021684250557f106d0bd67fa011c15bbb931f80e183a9391cabba65df3460b2125450fdd07c3906313c2bce0230a659cb6545ef6ebf511b8618815117598463546c2b114c50fb3bc927f085da77f995a967982c8120ab992efbba502972c34e01a8baf9f3639b50fcf916b51c5158fc2224a80c1e7eee6966cd5ba8bf124d6abd7fa1c8251bcada9650fd6371a1bb12b9d71835af774ccd44ae2fd60e3eb2b98b2223e8c0bd08e3a4bd1548fe4c50f56e75623d665ca50fffd8611d9870dea7b96ae4373e8af3282092a111f434a8f64c50fb23901d6d09e1b8c745854c728b1dc40ba6784ecf9085d55389e1072248b1291448fc4c50fd64f240e66aa83b5c5b19501585443dbe9df71a602b138e13c8e73efc8f1e2eeb48fe48ff04000000ab0000004c5000362c89bc119cd5c2eca42a5733e64308a4c8412f26b75dea714d7dddf659143a5001e12aaabbecb4aa79d22159294a21515e8f99baec6d462d7a0afbfbe8a1ed64315003a34ed8e29a7f8afebbcedba0dc0f634c9010bd77f8cebaf91d564ef83352fc84500413e8c831b7ed00c78cff7a4bd59b39e3467c66ac33ad80ee8248583c0b3e14f850057b0caea31148bd68f67f37bd39933e5f25abf7cea8938e6d6feaf1a01b91b03d000000000000000000000000",
            "0x55000000100000005500000055000000410000004230a3fb99579a733a84cfe53ee851c2b8c96c26bb356ee26d80a89ca294fb2257be4aeb05efc2a0201fdf81c0455ac220a9297207275b359ee0a8aa66fb5bbf01",
            "0x55000000100000005500000055000000410000004230a3fb99579a733a84cfe53ee851c2b8c96c26bb356ee26d80a89ca294fb2257be4aeb05efc2a0201fdf81c0455ac220a9297207275b359ee0a8aa66fb5bbf01",
            "0x55000000100000005500000055000000410000004230a3fb99579a733a84cfe53ee851c2b8c96c26bb356ee26d80a89ca294fb2257be4aeb05efc2a0201fdf81c0455ac220a9297207275b359ee0a8aa66fb5bbf01"
        ]
    },
    "tx_status": {
        "block_hash": "0x38569d4e871b1627846ad429a133bc333dde1fa9394a0211017644e52f18c1ec",
        "status": "committed"
    }
}
```

---

### l1TxHash
0x70bfcdb521930ba8de3ca5b8ae9094a7a90f1dbdbf76af5fa9ee7336fcf0ca81
### transaction with status: 
```JSON
{
    "transaction": {
        "cell_deps": [
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xb3de3dea316f8c04da9e04f81ee08ab871746046292b90288602b07ba88b67b7"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xc2d0b850618aa4bc6f833b6dfe921a6e718d376d24882d45d805149fd7290976"
                }
            },
            {
                "dep_type": "dep_group",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0x2db1b175e0436966e5fc8dd5cdf855970869b37a6c556e00e97ccb161c644eb5"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0x78387eaa0657e6a71b36f299fc515320d2fa2d9d452cd7d74dc9d8308cac3652"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xb50ba45f9c5d9e4a6b283c0f6fe50975dafebfc6b552107f03d49d3168efbdb2"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x1",
                    "tx_hash": "0x4954b63327fb2157c32c4606cdd5ab9556cf9bb9c8a8ec452c14b84b5d00a2a5"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0xe29e1370b02ca3bcb03150b72b22258e1618012e42c6110037d9c669202d80d8"
                }
            },
            {
                "dep_type": "code",
                "out_point": {
                    "index": "0x0",
                    "tx_hash": "0x8fdea291b961e6b60e9281e35e88c62f6d83739f5142e1de3eb5c635c822d8b3"
                }
            }
        ],
        "hash": "0x70bfcdb521930ba8de3ca5b8ae9094a7a90f1dbdbf76af5fa9ee7336fcf0ca81",
        "header_deps": [],
        "inputs": [
            {
                "previous_output": {
                    "index": "0x0",
                    "tx_hash": "0x8fdea291b961e6b60e9281e35e88c62f6d83739f5142e1de3eb5c635c822d8b3"
                },
                "since": "0x4000000060c22cc6"
            },
            {
                "previous_output": {
                    "index": "0x1",
                    "tx_hash": "0x8fdea291b961e6b60e9281e35e88c62f6d83739f5142e1de3eb5c635c822d8b3"
                },
                "since": "0x0"
            },
            {
                "previous_output": {
                    "index": "0x0",
                    "tx_hash": "0x3f66b988907a34ea860a8cf6873ed9372dd8e73479b00d401d8870bc822c0f7d"
                },
                "since": "0x0"
            },
            {
                "previous_output": {
                    "index": "0x2",
                    "tx_hash": "0xdd28a0a5bfda635e5f9c61a202242403576a38d810c6b2eecb58ff0c93966e24"
                },
                "since": "0x0"
            }
        ],
        "outputs": [
            {
                "capacity": "0x82c1f7f00",
                "lock": {
                    "args": "0x7840d20d8828ee4ea694fbc95f73e1513681e5d8ee3d866a72068c96ff25a25b6e2999a011d119bef85e3de804976d0c57d4d4a4c673f909024c266cf9e897c5",
                    "code_hash": "0x3bcd5dd6af0c2c1d865f787e648044f90177382288072c61c57bc989a2375f16",
                    "hash_type": "type"
                },
                "type": {
                    "args": "0x4912ea97674f287bc916f36c458cf5737214c370b9ffa9eea71836bda7248ff2",
                    "code_hash": "0x22034c8ad0710a83ba28bd41cd1cb1a0786e0fd984cbd20d81ba3219d52a1932",
                    "hash_type": "type"
                }
            },
            {
                "capacity": "0x3b9aca000",
                "lock": {
                    "args": "0x5f8e37cad738cd4d2e4317e57ece7809a794e31fcfb2694b11dffe2b739f7ac3",
                    "code_hash": "0xf70aa98a96fba847185be1b58c1d1e3cae7ad91f971eecc5749799d5e72939f0",
                    "hash_type": "type"
                },
                "type": {
                    "args": "0x6e2999a011d119bef85e3de804976d0c57d4d4a4c673f909024c266cf9e897c5",
                    "code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944",
                    "hash_type": "type"
                }
            },
            {
                "capacity": "0x318bde500",
                "lock": {
                    "args": "0x8c71916faa3b18d34e709575722810c65ba4d66ff005c4b7112bbf4e54f1afe43bab60cef4af81a87b0386f29bbf1dd0f6fe71c9fe1d84ca37096a6284d3bdaf2700000000000000",
                    "code_hash": "0xe70a7c0e8f5e18bbd6b6e5785df7e0dd5c41cc9d3c328ccb6f24bfddc96f970d",
                    "hash_type": "type"
                },
                "type": null
            },
            {
                "capacity": "0x12473cc1c24e",
                "lock": {
                    "args": "0x43d509d97f26007a285f39241cffcd411157196c",
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type"
                },
                "type": null
            }
        ],
        "outputs_data": [
            "0x72c14a3ca6d07c78c658113396865fdab50fadeec82f5abe82da7d74b348f982728cf0f482656e9c54c5764ccc5dc38cd38f58ea5a8da446e951d8792ddf27aa060000002ba0dff0704a99653b6e315c38c25b5d8a2c134414245b3e5b27df32742dbc3d280000000000000000000000000000000000000000000000000000000000000000000000000000008dd33585b29a9d06271dc6eb7ee6c8de15705f1241b8f80379079263d4b3bebb130000000000000000",
            "0xc62cc26000000000c62cc26000000000000000000000",
            "0x",
            "0x"
        ],
        "version": "0x0",
        "witnesses": [
            "0x7202000010000000550000005500000041000000cefdc0c2fbabd53f5df09894e52acd0a3c7eab193311109d3efc4d2d9e4b8af856cd121e02aca6f816e61d3bf328982619df56592e850e4de92b3b925db7c36101190200000000000015020000100000000d02000011020000fd0100001c0000006001000064010000680100006c010000f9010000440100002c0000003400000038000000580000007800000080000000a4000000c8000000cc000000f0000000270000000000000000000000f8a5986bc0150a711b16deb0c070602931247f0d0421316e45a06f771643dcb43bab60cef4af81a87b0386f29bbf1dd0f6fe71c9fe1d84ca37096a6284d3bdaf746380f679010000728cf0f482656e9c54c5764ccc5dc38cd38f58ea5a8da446e951d8792ddf27aa06000000728cf0f482656e9c54c5764ccc5dc38cd38f58ea5a8da446e951d8792ddf27aa0600000000000000000000000000000000000000000000000000000000000000000000000000000000000000540000001000000030000000340000000000000000000000000000000000000000000000000000000000000000000000000000009dd8e7639ac231fda0d7d235dec76c6b86d540d51d1d91b496522c6968f7c89b040000000000000004000000890000004c50000104caa6501ef3b36596e61468ab5933276205a791034cbc4dfc7e9eea4c092d500130cd239159b0526df213515884266c9a2ae5648b67a643389894880fcb2a1d315002e72644e7d85ba039fde1a65ce4ecce214dd18b4566264aedc83935b724e6834450057b0caea31148bd68f67f37bd39933e5f25abf7cea8938e6d6feaf1a01b91b03d000000000000000000000000",
            "0x55000000100000005500000055000000410000003b831febd4b5db921ad145b9644dac436212f1cf9d9cfba7ccca6bf91b8d82e643946f55d5a46ec2cacac6ee2d67340220252141bed8f3ce276b1ddee855942c00",
            "0x55000000100000005500000055000000410000003b831febd4b5db921ad145b9644dac436212f1cf9d9cfba7ccca6bf91b8d82e643946f55d5a46ec2cacac6ee2d67340220252141bed8f3ce276b1ddee855942c00",
            "0x55000000100000005500000055000000410000003b831febd4b5db921ad145b9644dac436212f1cf9d9cfba7ccca6bf91b8d82e643946f55d5a46ec2cacac6ee2d67340220252141bed8f3ce276b1ddee855942c00"
        ]
    },
    "tx_status": {
        "block_hash": "0xba087e6f3bee5171424d04833317ff1cb17b896906c0f14cc3c27ff6b5465901",
        "status": "committed"
    }
}
```

**Comment by jjyr** [comment]
@zeroqn can you help us to identify this error?

**Comment by zeroqn** [comment]
> |     Submitted l2 block 60 in tx cd0c598c42acc298a0790dc381fab0bf472f3ca8bdb8136b1b49b77b1731c12b
godwoken_1   | [2021-06-10T15:27:14Z INFO  gw_block_producer::block_producer] produce new block #60 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 1)

Hmmm, two 60 blocks?

**Comment by jjyr** [comment]
> > |     Submitted l2 block 60 in tx cd0c598c42acc298a0790dc381fab0bf472f3ca8bdb8136b1b49b77b1731c12b
> > godwoken_1   | [2021-06-10T15:27:14Z INFO  gw_block_producer::block_producer] produce new block #60 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 1)
> 
> Hmmm, two 60 blocks?

I think the reason is the submitting transaction contains two duplicated inputs, see the error message, there are two duplicated outpoint `0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000` https://github.com/nervosnetwork/godwoken-tests/pull/5

**Comment by zeroqn** [comment]
> > > |     Submitted l2 block 60 in tx cd0c598c42acc298a0790dc381fab0bf472f3ca8bdb8136b1b49b77b1731c12b
> > > godwoken_1   | [2021-06-10T15:27:14Z INFO  gw_block_producer::block_producer] produce new block #60 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 1)
> > 
> > 
> > Hmmm, two 60 blocks?
> 
> I think the reason is the submitting transaction contains two duplicated inputs, see the error message, there are two duplicated outpoint `0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000` #5

`0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c8000000000` is rollup cell. We also use rollup cell as cell dep to reuse unlocked stake cell, so we end up with two outpoint `0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c8000000000`. This is expected.

Last finalized block number in decode global state is 39 and block finality is 20. Next block number is indeed 60. But why it produce 60 twice? Since 60 was already submitted in tx  `cd0c598c42acc298a0790dc381fab0bf472f3ca8bdb8136b1b49b77b1731c12b`.

`0x70bfcdb521930ba8de3ca5b8ae9094a7a90f1dbdbf76af5fa9ee7336fcf0ca8102000000` is stake cell. The stake block number is 39, it's unlocked in 59.

**Comment by zeroqn** [comment]
> godwoken_1   |     Submitted l2 block 60 in tx cd0c598c42acc298a0790dc381fab0bf472f3ca8bdb8136b1b49b77b1731c12b
godwoken_1   |     
godwoken_1   | [2021-06-10T15:26:56Z INFO  gw_block_producer::runner] received new layer1 block 380, e122e81d4e27882e1e9d3394985996634217114889b45dae2cb3c99d3a887d21
godwoken_1   | [2021-06-10T15:26:59Z INFO  gw_block_producer::runner] received new layer1 block 381, 9e9d8ade43a16c4fe1b4afd4f5a7e1cd7f972d23877f6bdb5b217466a3d5cadb
godwoken_1   | [2021-06-10T15:27:05Z INFO  gw_block_producer::runner] received new layer1 block 382, f3ae9090bacbf436903bf8673324b96b95453b7644e7870c91bbabacd92e4ebd
godwoken_1   | [2021-06-10T15:27:11Z INFO  gw_block_producer::runner] received new layer1 block 383, 971214aacbff6505ab54e2b2648e8faa404de6c097259950cd8729fd54043095
godwoken_1   | [2021-06-10T15:27:14Z INFO  gw_block_producer::runner] received new layer1 block 384, f70f494c075b0ac00371f7586849e70c7f5a07ce647f43c1c345736f8241d64d
godwoken_1   | [2021-06-10T15:27:14Z INFO  gw_block_producer::block_producer] produce new block #60 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 1)
godwoken_1   | [2021-06-10T15:27:14Z ERROR gw_block_producer::block_producer] Submitting l2 block error: JSONRPC error: Server error: TransactionFailedToResolve: Resolve failed Unknown([OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000), OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80001000000), OutPoint(0x70bfcdb521930ba8de3ca5b8ae9094a7a90f1dbdbf76af5fa9ee7336fcf0ca8102000000), OutPoint(0xad029bce36d1c297e53bc91aaf931a7bc6a4299a7f10929b336169c74c71c80000000000)])
godwoken_1   | [2021-06-10T15:27:20Z INFO  gw_block_producer::runner] received new layer1 block 385, 979868aac87102ad7d2b6dca0dbee9da9f9808c11bcef5a1e2ce20b662088a2c
godwoken_1   | [2021-06-10T15:27:20Z INFO  gw_block_producer::block_producer] produce new block #61 (txs: 0, deposits: 0, staled txs: 0, staled withdrawals: 0)
godwoken_1   | [2021-06-10T15:27:20Z INFO  gw_block_producer::block_producer] 
godwoken_1   |     Submitted l2 block 61 in tx f1cef95bf84c4f9d87df2ca40cd24256f337bf320d7a65707bb126be3c9ab2d2
godwoken_1   |     
godwoken_1   | [2021-06-10T15:27:26Z INFO  gw_block_producer::runner] received new layer1 block 386, 6f2e322f6455df9491134afb42f8deff123ba17a1e7ceb74708c36107856706f

I think tx `cd0c598c42acc298a0790dc381fab0bf472f3ca8bdb8136b1b49b77b1731c12b` (aka l2 block #60) was committed in l1 block 385, so we produce block #60 again.  

We should increase poa ```round_intervals``` from 24 to 40.

**Pull request merged**
